apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId:	ticketing-dev-405307
  artifacts:
    - image: us.gcr.io/ticketing-dev-405307/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'scr/**/*.ts'
            dest: .